//export const ROOT           =      'http://192.168.0.154:8000'
export const ROOT           =      'http://54.37.227.57'
export const API_URL        =      ROOT +       '/api'
export const LOGIN          =      API_URL +    '/auth/login'
export const POSTS          =      API_URL +    '/posts'
export const POSTS_TEST     =      API_URL +    '/posts/test?amount=10&page=1'
export const IMG            =      ROOT +       '/storage/'
export const USER_AUTH      =      API_URL +    '/users/auth'
export const USER           =      API_URL +    '/users/find'
export const COMMENTS       =      API_URL +    '/comments'
