//export CONSTS with mutations names
export const SET_POSTS                      = 'setPosts';
export const SET_POST_BY_ID                 = 'setPostById';
export const SET_POSTS_OBJ                  = 'setPostsObject';
export const SET_TOKEN                      = 'setToken';
export const SET_LOADING                    = 'loading';
export const SET_COMMENTS                   = 'setComments';
export const SET_CURRENT_POST               = 'setCurrentPost';
export const SET_CURRENT_POST_INDEX         = 'setCurrentPostIndex';
export const SET_CURRENT_COMMENT            = 'setCurrentComment';
export const SET_LOGED_USER                 = 'setLogedUser';
export const SET_CACHED_COMMENTS            = 'setCachedComments';
export const RESET_DEFAULT_COMMENTS         = 'resetDefaultComments';
export const SET_LOAD_MORE_COMMENTS         = 'setLoadMoreComments';
export const SET_USER_POSTS                 = 'setUserPosts';
export const SET_POST_DETAILS_STATE         = 'setPostDetailsState';
export const SET_COMMENTS_DETAILS_STATE     = 'setCommentsDetailsState';
